name: CI Process

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'data/**.json'
env:
  folder: petr001

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.folder }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Run something
        working-directory: petr001
        run: |
          chmod +x test.sh
          ./test.sh




