name: CI Process
on:
  push:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'skip'
        type: boolean
        default: false
      myInput:
        type: boolean
        required: false

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
    second_job:
        runs-on: ubuntu-latest
      - uses: ./.github/workflows/resuable.yml
        with:
          myInput: ${{ inputs.myInput }}


