name: CI Process

on:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'Skip the second job'
        required: false
        type: boolean
        default: false
      create_release:
        description: 'fdfd'
        type: boolean
        default: false
  push:

jobs:
  first_job:
    continue-on-error: ${{ github.event_name == 'push' && inputs.skip != 'false' && inputs.create_release != 'false' }}
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.fail_me.outputs.SKIP }}
    steps:
      - uses: actions/checkout@v4
      - name: Fail me
        id: fail_me
        run: |
          echo "push ${{ github.event_name == 'push' }}"
          echo " create_release: ${{ inputs.create_release != 'false' }}"
          echo " skip: ${{ inputs.skip != 'false' }}"
          echo " all of this: ${{ github.event_name == 'true' && inputs.skip != 'false' && inputs.create_release != 'false' }}"
          echo "SKIP=${{ github.event.inputs.skip_me == 'true' }}" >> $GITHUB_OUTPUT
          exit 1

  second_jobs:
    needs: first_job
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: Write me
        run: |
          echo "Hello"
