name: CI-MAIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  workflow_call:
jobs:
    villa:
       name: Villa Build FE
       uses: /villa/.github/workflows/frontend.yml@main

