name: CI Process

on:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'Skip the second job'
        required: false
        type: boolean
        default: false
      hello:
        description: 'fdfd'
        type: string
        default: 'hello'
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Fail me
        id: fail_me
        run: |
          exit 1

  second_jobs:
    needs: first_job
    runs-on: ubuntu-latest
    if: ${{ needs.first_job.result == 'failure' }}
    steps:
      - name: Write me
        run: |
          echo "Hello"
