name: CI-MAIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
jobs:
  villa:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo hello

