name: CI Process
on:
  push:
  workflow_dispatch:
    inputs:
      isLatest:
        description: 'Is this the latest version?'
        required: false
        default: true
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Determine if push with latest
        id: set_tags
        run: |
          echo "TAGS=firstCondition" >> $GITHUB_OUTPUT
          if [[ "${{ github.event.inputs.isLatest }}" == 'true' ]]; then
            echo "TAGS=1,latest" >> $GITHUB_OUTPUT
          fi
      - name: print version
        run: |
          echo "Versions are: ${{ steps.set_tags.outputs.TAGS}}"
