name: CI Process

on:
  pull_request:
    branches:
      - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Run something
        run: |
          echo "Running something"
