name: CI Process
on:
  push:
  workflow_dispatch:
    inputs:
      isLatest:
        description: 'Is this the latest version?'
        required: false
        default: 'false'
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Determine if push with latest
        id: set_tags
        env:
          IS_LATEST: ${{ github.event.inputs.isLatest }}
        run: |
          echo "Input isLatest: $IS_LATEST"
          echo "TAGS=firstCondition" >> $GITHUB_ENV
          if [ "$IS_LATEST" == "true" ]; then
            echo "TAGS=1,latest" >> $GITHUB_ENV
          fi
      - name: print version
        run: |
          echo "Versions are: $TAGS"
