name: CI Process

on:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'Skip the second job'
        required: false
        type: boolean
        default: false
      create_release:
        description: 'fdfd'
        type: boolean
        default: false
  push:

jobs:
  first_job:
    continue-on-error: ${{ !inputs.create_release }}
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.fail_me.outputs.SKIP }}
    steps:
      - uses: actions/checkout@v4
      - name: Fail me
        id: fail_me
        run: |
          exit 1
      - name: Report status
        if: failure()
        run: |
          echo "step has status: ${{ steps.fail_me.outcome }}"

  second_jobs:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Write me
        run: |
          echo "Hello"
