name: CI Process
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Run something
        run: |
          echo testfdfd




