name: CI Process

on:
  push:
env:
  folder: petr001

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test.yaml@petr-test
        with:
          my_var: ${{ vars.MUJ_VAR }}





