name: CI Process

on:
  push:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'Skip the second job'
        required: false
        type: boolean
        default: false

jobs:
  first_job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.fail_me.outputs.SKIP_ME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Fail me
        continue-on-error: true
        id: fail_me
        run: |
          echo "SKIP_ME=${{ github.event.inputs.skip_me }} >> $GITHUB_OUTPUT"
          exit 1

  second_jobs:
    if: ${{ needs.first_job.result != 'success'}}
    needs:
    - first_job
    runs-on: ubuntu-latest
    steps:
      - name: Write me
        run: |
          echo "I have run"
