name: CI Process

on:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'Skip the second job'
        required: false
        type: boolean
        default: false
      hello:
        description: 'fdfd'
        type: string
        default: 'hello'
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.fail_me.outputs.SKIP }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Fail me
        id: fail_me
        run: |
          echo "SKIP=${{ github.event.inputs.skip_me == 'true' }}" >> $GITHUB_OUTPUT
          exit 0

  second_jobs:
    needs: first_job
    runs-on: ubuntu-latest
    if: ${{ failure() || success() }} && ${{ needs.first_job.outputs.SKIP == 'true' }}
    steps:
      - name: Write me
        run: |
          echo "Hello"
