name: CI Process

on:
  pull_request:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Run something
        run: |
          echo "Running something"

  on_success_job:
    runs-on: ubuntu-latest
    needs: my_first_job
    if: >
      github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
      - name: Do something
        run: |
          echo "CI Process was successful on a pull request, doing something..."
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          
          MAJOR_VERSION=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR_VERSION=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH_VERSION=$(echo $LATEST_TAG | cut -d. -f3)
          
          NEW_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$((PATCH_VERSION + 1))"
          
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
