name: CI Process

on:
  workflow_dispatch:
    inputs:
      skip_me:
        description: 'Skip the second job'
        required: false
        type: boolean
        default: false
      hello:
        description: 'fdfd'
        type: string
        default: 'hello'
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.fail_me.outputs.SKIP_ME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Fail me
        id: fail_me
        run: |
          echo "${{ github.event.inputs.hello }}"
          echo "SKIP_ME=${{ github.event.inputs.skip_me }}" >> $GITHUB_OUTPUT
          exit 1

  second_jobs:
    if: always()
    needs:
    - first_job
    runs-on: ubuntu-latest
    steps:
      - name: Write me
        run: |
          echo "${{ needs.first_job.result }}"
          echo "${{ needs.first_job.result == 'failure' && needs.first_job.outputs.skip == 'true' }}"
