name: On Success


jobs:
  on_success_job:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    steps:
      - uses: actions/checkout@v2
      - name: Do something
        run: |
          echo "CI Process was successful on a pull request, doing something..."
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
  
          MAJOR_VERSION=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR_VERSION=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH_VERSION=$(echo $LATEST_TAG | cut -d. -f3)
  
          NEW_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$((PATCH_VERSION + 1))"
  
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
