name: On Success

on:
  workflow_run:
    workflows: ["CI Process"]
    types:
      - completed

jobs:
  on_success_job:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Do something
        run: echo "CI Process was successful on a pull request, doing something..."
