name: On Success

on:
  workflow_run:
    workflows: ["CI Process"]
    types:
      - completed
    push:
      branches:
        - main
jobs:
  on_success_job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "CI Process was successful on a pull request, doing something..."
