name: on success

on:
  pull_request_target:
    types: [ closed ]

env:
  folder: petr002

jobs:
  on_success_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        uses: actions/checkout@v2
      - name: Do something when merged to main
        run: |
             touch creds
             git config --global credential.helper 'store --file creds'
             echo "https://${{secrets.GITHUB_TOKEN}}:x-oauth-basic@github.com" > creds
             export EDITOR=nano
             git config --global user.name 'GitHub Actions'
             git config --global user.email 'actions@github.com'
             git fetch --tags
        
             latest_tag=$(git tag -l "Release_v_*" | sort -V | tail -n 1)

             if [[ $latest_tag == "" ]]; then
             next_tag_num=1
             else
             current_num=${latest_tag#Release_v_}
             next_tag_num=$((current_num + 1))
             fi
             git tag "Release_v_$next_tag_num"
             git push origin "Release_v_$next_tag_num"
        shell: bash







