name: on success

on:
  pull_request_target:
    types: [closed]
  workflow_run:
    workflows: ["CI Process"]
    types: [completed]

env:
  folder: petr001

jobs:
  on_success_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do something when merged to main
        run: |
          touch creds
          git config --global credential.helper 'store --file creds'
          echo "https://${{secrets.GITHUB_TOKEN}}:x-oauth-basic@github.com" > creds
          export EDITOR=nano
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
           git tag -a 1.1.1 -m "Tagged version 1.1.1"
