name: Reusable
on:
  workflow_call:
    inputs:
        type: boolean
        required: false

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
        run:
          echo ${{ inputs.myInput }}

